<div class = "push-right">
    <div class = "contentWrapper">
        <div class="headElement">
            <img src="IMG/calander.png" alt="Calander" class="inline-image">
            <h2 class="inline-text">Admin</h2>
        </div>
        <div id = "adminOptions">
            <ul>
                <li><a href="ManagePLF.php">Manage PLFs</a></li>
                <li>Manage Staff</li>
                <li>Manage Individual Shifts</li>
                <li>View Abenties</li>
            </ul>
        </div>
    </div>
</div>