<div class = "push-right">
    <div id = "dashboard">
        <div class = "notification">
            <p>(IT) Hayden Jackson is asbent Tuesday, at 12:00pm</p>
            <p>(IT) Anthony Price is asbent Wednesday, at 1:00pm</p>
            <p>11:00am</p>
        </div>
        <div class = "notification">
            <p>Louis Van Dyke has reached 20 hours!</p>
            <p>10:00am</p>
        </div>
    </div>
</div>