<?php
    /*
    Global header includes
    */
?>
<title>STIMulate</title>
<link href="CSS/Header.CSS" rel="stylesheet" type="text/css">
<link href="CSS/Global.CSS" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
<link href="https://qutvirtual3.qut.edu.au/images/qut/template/favicon.ico" rel="Shortcut Icon" />
<script src = "JS/jQuery.js" type="text/javascript"></script>
<script src="JS/SideBar.js" ></script>