<header>
    <div id = "logo">
        <img src="IMG/QUT.png" alt="QUT Logo" class = "inline-image">
        <h1 class = inline-text>STIMulate</h1>
    </div>
    <div id = "user-information">
        <ul>
            <li id = "latest-information">
                <img src="IMG/latest.png" alt = "latest information picture" class = "inline-image">
                <p class = "notificationNumber inline-text">2</p>
            </li>
            <li id = "user-notifications">
                <img src="IMG/notification.png" alt = "user notification picture" class = "inline-image">
                <p class = "notificationNumber inline-text">6</p>
            </li>
            <li id = "loginButton">
                <img src="IMG/student.png" alt = "student Picture" class = "inline-image">
                <p id = "studentName" class = "inline-text">Hayden Jackson</p>
            </li>
        </ul>
    </div>
</header>